[package]
name = "eutracker-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "5.1.0"
regex = "1.8.1"
rust_decimal = "1.29.1"
tui = "0.19.0"
